### PR TITLE
Fixes nft keyword collision

### LINKED ISSUE #216: Unable to start pod named `log` due to conflict in keyword with NFT
When I run this workload 
```
apiVersion: management.project-flotta.io/v1alpha1
kind: EdgeWorkload
metadata:
  name: log
spec:
  deviceSelector:
    matchLabels:
      app: webcam
  type: pod
  pod:
    spec:
      containers:
        - name: log
          image: docker.io/eloycoto/logexample

```

it fails due to this error shown in the device's log:

```
Jul 28 11:38:59 fedora yggdrasild[837]: [yggdrasild] 2022/07/28 11:38:59 /usr/libexec/yggdrasil/device-worker: failed to delete chain 'log' from table 'edge' for workload 'log': running [/usr/sbin/nft list chain inet edge log]: exit status 1: Error: syntax error, unexpected log, expecting string
Jul 28 11:38:59 fedora yggdrasild[837]: [yggdrasild] 2022/07/28 11:38:59 /usr/libexec/yggdrasil/device-worker: list chain inet edge log
Jul 28 11:38:59 fedora yggdrasild[837]: [yggdrasild] 2022/07/28 11:38:59 /usr/libexec/yggdrasil/device-worker:                      ^^^
```

Proposed solution is to prepend with `wl-` the chain name to avoid hitting keywords in nft and being able to still meet the max length requirements in NFT and kubernetes.

### PR DESCRIPTION
**Pull request by jordigilh**
Fixes #216

### CODE REVIEW

File: internal/workload/network/netfilter.go [hunk 1]
```diff
@@ -66,13 +66,17 @@ func (nft *netfilter) DeleteTable(table string) error {
 }
 
 func (nft *netfilter) AddChain(table, chain string) error {
-	args := []string{"add", "chain", family, table, chain, "{ type filter hook input priority 0 ; }"}
+	// Fixes https://github.com/project-flotta/flotta-device-worker/issues/216
+	chainName := fmt.Sprintf("wl-%s", chain)
```
Comment (masayag) [inline internal/workload/network/netfilter.go:70]: Pls extract `fmt.Sprintf("wl-%s", chain)` to a method.
It is repeated twice and should be defined only once to avoid future issues.

Comment (jordigilh) [reply internal/workload/network/netfilter.go:70]: Will do.

Comment (jordigilh) [reply internal/workload/network/netfilter.go]: Done

**Review by masayag — APPROVED** [review]

**Comment by masayag** [comment]
@jordigilh  Pls rebased.

**Review by eloycoto — APPROVED** [review]
